{{- with .Values.metaMonitoring.grafanaAgent }}
{{- if .enabled }}
apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" $ "component" "meta-monitoring") }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    {{- include "mimir.labels" (dict "ctx" $ "component" "meta-monitoring" ) | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceAccountName: {{ include "mimir.resourceName" (dict "ctx" $ "component" "grafana-agent") }}
  logs:
    instanceSelector:
      matchLabels:
        {{- include "mimir.selectorLabels" (dict "ctx" $ "component" "meta-monitoring") | nindent 8 }}
    # cluster label for logs is added in the LogsInstance
  metrics:
    instanceSelector:
      matchLabels:
        {{- include "mimir.selectorLabels" (dict "ctx" $ "component" "meta-monitoring") | nindent 8 }}
    externalLabels:
      cluster: {{ include "mimir.clusterName" $ }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" $ "component" "grafana-agent") }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    {{- include "mimir.labels" (dict "ctx" $ "component" "meta-monitoring" ) | nindent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" $ "component" "grafana-agent") }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    {{- include "mimir.labels" (dict "ctx" $ "component" "meta-monitoring" ) | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - endpoints
      - pods
      - events
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
      - /metrics/cadvisor
    verbs:
      - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" $ "component" "grafana-agent") }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    {{- include "mimir.labels" (dict "ctx" $ "component" "meta-monitoring" ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mimir.resourceName" (dict "ctx" $ "component" "grafana-agent") }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mimir.resourceName" (dict "ctx" $ "component" "grafana-agent") }}
    namespace: {{ .namespace | default $.Release.Namespace }}
{{- end }}
{{- end }}
