{{- if .Values.metaMonitoring.grafanaAgent.enabled }}
{{- with .Values.metaMonitoring.grafanaAgent.logs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" $ "component" "logs-instance-usernames") }}
  labels:
    {{- include "mimir.labels" (dict "ctx" $ "component" "logs-instance-usernames") | nindent 4 }}
data:
  default: {{ .remote.basicAuth.username | b64enc }}
  {{- range $i, $cfg := .additionalClientConfigs }}
  additional-{{ $i }}: {{ $cfg.basicAuth.username | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
