name: compare-helm-with-jsonnet

on:
  push:
    branches:
      - logiraptor/use-k8s-diff

jobs:
  compare-manifests:
    runs-on: ubuntu-latest
    steps:
    - uses: grafana/k8s-diff/setup-k8s-diff@add-github-actions
    - run: |
        echo "which yaml-patch" $(which yaml-patch)
        echo "which config-defaults" $(which config-defaults)
        echo "which config-generate" $(which config-generate)
        echo "which k8s-defaults" $(which k8s-defaults)
      shell: bash
    # - uses: grafana/k8s-diff/cmd/yaml-patch@add-github-actions
    #   with:
    #     input-dirs: operations/helm/tests/test-oss-values-generated,operations/mimir-tests/
    #     output-dirs: operations/scratch/helm,operations/scratch/jsonnet
    #     rules-files: operations/helm/k8s-diff/ignore_missing_objects.yaml,operations/k8s-diff/fix_k8s_names.yaml
