name: compare-helm-with-jsonnet

on:
  push:
    branches:
      - logiraptor/use-k8s-diff

jobs:
  compare-manifests:
    runs-on: ubuntu-latest
    steps:
    - uses: grafana/k8s-diff/setup-k8s-diff@add-github-actions
    - run: ./operations/helm/k8s-diff/compare-with-jsonnet
      shell: bash
